name: Test CI 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up build project
        run: npm install && npm run build

      - name: Run test inside web container
        run: echo "Mock CI/CD complete succesfully"